#!/usr/bin/env python3
# // my comment


from pymongo import MongoClient

# connect to the Mongodb server
client = MongoClient('localhost', 27017)

# Access the school collection in the db database
db = client.db
collection = db.school

# Insert a document into the school collection
collection.insert_one({"name": "Holberton school"});
